### ISSUE TITLE
Job exiting due to SCR_FINALIZE_CALLED 

### ISSUE THREAD

**Issue by lwan86** [LLNL/scr#13]
My code worked well with previous version of SCR (I couldn't remember which version).
Last week I upgraded the SCR source code to the newest version in the github repo and recompile it. However, when I tried to run my code, it always exits before the function SCR_Init() finishes. The debugging info says the reason the job exits is because "SCR_FINALIZE_CALLED". Why the SCR_Finalize is called during the SCR_Init()? I located the problem happened in function "scr_bool_check_halt_and_decrement()", but I don't understand why it happened. I was wondering if someone could help me on this. Thanks!

**Comment by adammoody** [comment]
Hi @lwan86.  You likely just need to remove the SCR_FINALIZE_CALLED condition from the halt file or just delete the halt file.  You can do that by running the following command:

  scr_halt --remove

This is behavior is confusing at first, but it's actually by design.  We use the call to SCR_Finalize() as the way for the application to signal that it has completed.  Without such a signal, the SCR library and its associated scripting would assume the job ended unexpectedly and continue to restart it forever.  SCR_Finalize acts as a break to the infinite loop.  It does this by recording the fact that SCR_Finalize was called in the halt file.  If the library detects this condition in the halt file, it will not restart the application.

Although this is by design, it does lead to lots of confusion.  I'll keep this ticket open as a reminder to revisit this to improve things.

**Comment by lwan86** [comment]
Thanks for your suggestion, @adammoody! I deleted the halt.scr file directly and it works now.

**Comment by adammoody** [comment]
Due to massive confusion over this "feature", we've disabled SCR_Init from bailing if SCR_FINALIZE_CALLED is set in the halt file.  We'll assume the job was restarted intentionally in this case.  The fix is available starting with commit bc040fe89bea82b245d75f99dcb259fa55ba4f99.
