### ISSUE TITLE
AXL_KEY_CONFIG_RANK undeclared

### ISSUE THREAD

**Issue by Quentin-Anthony** [LLNL/scr#398]
Currently, AXL_KEY_CONFIG_RANK is used in scr.c [here](https://github.com/LLNL/scr/commit/2152d103b2f08a37ae42f8bdafa88b3d7a761c11#diff-b508febc113fb14b5c2a383a5e862532033c58fd8202224e62f24fc1b712c081)

However, AXL_KEY_CONFIG_RANK wasn't introduced until after axl v0.4.0 ([see here](https://github.com/ECP-VeloC/AXL/commit/47a08f0e70481fbab7abc243dbbaac84bbe9def9)), which is newer than the version checked out in bootstrap.sh ([see here](https://github.com/LLNL/scr/blob/develop/bootstrap.sh#L157))

This leads to build errors if build_dev = 0 in bootstrap.sh:

```
/usr/workspace/anthony/xscale/scr-work/scr-exa/src/scr.c: In function 'SCR_Init':
/usr/workspace/anthony/xscale/scr-work/scr-exa/src/scr.c:2148:7: error: 'AXL_KEY_CONFIG_RANK' undeclared (first use in this function); did you mean 'AXL_KEY_CONFIG_MKDIR'?
       AXL_KEY_CONFIG_RANK, scr_my_rank_world) != KVTREE_SUCCESS)
       ^~~~~~~~~~~~~~~~~~~
       AXL_KEY_CONFIG_MKDIR
/usr/workspace/anthony/xscale/scr-work/scr-exa/src/scr.c:2148:7: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [src/CMakeFiles/scr_o.dir/scr.c.o] Error 1
```

@adammoody -- Is this the intended behavior of build_dev?

**Comment by adammoody** [comment]
Thanks, @Quentin-Anthony .  Yeah, our build has been a moving target.  I think it should work if you add the ``--dev`` option in a fresh build:
```
./bootstrap.sh --dev
```
With the rc1 release, we were expecting end users to download and build most of the SCR components using the ``bootstrap.sh`` script.  If not given the ``--dev`` option, ``bootstrap.sh`` checkouts a particular tag of each one.  However, we forgot to include the corresponding ``git checkout`` that one needs to execute to back up to an SCR version that matches up.

Starting with rc2, we don't expect normal SCR users to mess with ``bootstrap.sh`` -- only developers will typically use it.  Normal users will install SCR with Spack or using a release tarball.  The release tarball includes source for all components, so there is no need to download and build them individually.

**Comment by adammoody** [comment]
Oh, for normal users, we do specify the ``git checkout v3.0rc1`` step in our build instructions:

https://scr.readthedocs.io/en/v3.0rc1/users/build.html#cmake

So we're good for normal users documentation wise.

**Comment by adammoody** [comment]
To sum all of that up, for normal users with rc1, the build is:
https://scr.readthedocs.io/en/v3.0rc1/users/build.html#cmake
```
git clone git@github.com:llnl/scr.git
cd scr
git checkout v3.0rc1

./bootstrap.sh

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=../install ..
make install
```
That is, clone SCR, git checkout v3.0rc1, bootstrap.

With rc2 and later, it will change to something like:
https://scr.readthedocs.io/en/latest/users/build.html#cmake
```
wget https://github.com/LLNL/scr/releases/download/v3.0rc2/scr-top-v3.0rc2.tgz
tar -zxf scr-top-v3.0rc2.tgz
cd scr-top-v3.0rc2

mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=../install ..
make -j install
```
Download release tarball (no clone, no checkout, no bootstrap).

For developers, it looks like:
https://github.com/llnl/scr#developers
```
git clone https://github.com/LLNL/scr.git
cd scr

./bootstrap.sh --dev --debug

cd build
cmake -DCMAKE_INSTALL_PREFIX=../install ..
make install
```
Clone SCR and ``bootstrap.sh --dev``.

Since we don't expect normal users to need ``bootstrap.sh`` starting with rc2, we could probably drop the ``--dev`` option and always have it build the latest commits of everything to simplify developer builds.

**Comment by adammoody** [comment]
If you'd like to explore what the release tarball for rc2 will look like, you can generate one with:
```
cd dist
./builddist develop
```
That produces an ``scr-top-develop.tgz``.  We'll use that same process to generate the eventual ``scr-top-v3.0rc2.tgz`` release tarball to attach to the github release page.

**Comment by adammoody** [comment]
Thanks for reporting this problem @Quentin-Anthony .  I think this should be fixed now.  The bootstrap includes git checkout commands for specific tags when given the ``--tag`` option.  It builds ``--dev`` by default.  Non-developers can use the release tarball to avoid these extra steps altogether.  I'll close this out assuming it's fixed.  Please reopen if you find otherwise.
