### ISSUE TITLE
Multiple applications picking up same SCR data

### ISSUE THREAD

**Issue by gonsie** [LLNL/scr#56]
I am trying some testing and it seem like multiple applications will pick up the same SCR data.

Notably, I'm trying to run the test_api example as well as some of the heatdis veloc examples. Is this known/expected behavior? Does each application calling SCR need their own install of the library?

**Comment by gonsie** [comment]
never mind, SCR was finding data in /tmp (since I didn't clean it out between runs)

**Comment by adammoody** [comment]
The data written to cache locations like /tmp assumes that the user is only one simulation as part of the current job.  We could perhaps support a case in which multiple simulations run on the same nodes in the same allocation.  For that, we'd need to extend the API to take something like a "simulation name" so that we can separate the data.

**Comment by adammoody** [comment]
The new SCR_CACHE_PURGE option helps a bit.  I'll go ahead and close this out in case this resurfaces as an annoying issue.
